from pathlib import Path
from types import SimpleNamespace

import pytest

import ros_project_creator.ros_project_creator as ros_project_creator_module
from ros_project_creator.ros_project_creator import RosProjectCreator, RosProjectCreatorException
from ros_project_creator.vscode_project_creator import VscodeProjectCreator, VscodeProjectCreatorException


@pytest.fixture
def fake_active_user(monkeypatch: pytest.MonkeyPatch, tmp_path: Path) -> Path:
    user_home = tmp_path / 'home'
    user_home.mkdir()

    monkeypatch.setenv('USER', 'developer')
    monkeypatch.delenv('SUDO_USER', raising=False)
    monkeypatch.setattr(
        ros_project_creator_module.pwd,
        'getpwnam',
        lambda username: SimpleNamespace(pw_dir=str(user_home)),
    )

    return user_home


@pytest.fixture
def fake_docker_generator(monkeypatch: pytest.MonkeyPatch):
    calls = []

    def generate_docker_context(config):
        calls.append(config)
        output_dir = Path(config.output_dir)
        output_dir.mkdir(parents=True)
        output_dir.joinpath('Dockerfile').write_text('# generated by robotics_dockers\n')
        output_dir.joinpath('build.py').write_text('# generated by robotics_dockers\n')
        output_dir.joinpath('docker-compose-dev.yaml').write_text('services: {}\n')
        output_dir.joinpath('.resources').mkdir()

    monkeypatch.setattr(ros_project_creator_module, 'generate_docker_context', generate_docker_context)
    return calls


def test_create_ros2_project_delegates_docker_generation(fake_active_user: Path, fake_docker_generator) -> None:
    project_dir = fake_active_user / 'demo_project'

    RosProjectCreator(
        project_id='demo',
        project_dir=project_dir,
        ros_distro='jazzy',
        base_img='ros:jazzy',
        image_main_user='developer',
        img_id='demo:latest',
        use_vscode_project=False,
        use_pre_commit=False,
        use_console_log=False,
    )

    assert len(fake_docker_generator) == 1
    docker_config = fake_docker_generator[0]
    assert docker_config.image_main_user == 'developer'
    assert docker_config.ros_distro == 'jazzy'
    assert docker_config.img_id == 'demo:latest'
    assert docker_config.output_dir == project_dir / 'docker'
    assert docker_config.rosdep_packages_dir == '../src'

    assert project_dir.joinpath('docker/Dockerfile').is_file()
    assert project_dir.joinpath('docker/build.py').is_file()
    assert project_dir.joinpath('docker/docker-compose.yaml').is_file()
    assert project_dir.joinpath('docker/.resources').is_dir()
    assert not project_dir.joinpath('docker/docker-compose-dev.yaml').exists()

    assert project_dir.joinpath('deps.repos').is_file()
    assert project_dir.joinpath('src/0_deps').is_dir()
    assert project_dir.joinpath('src/bringup/package.xml').is_file()
    assert project_dir.joinpath('src/simulation/package.xml').is_file()


def test_create_ros2_project_with_vscode_renders_templates(
    fake_active_user: Path,
    fake_docker_generator,
) -> None:
    project_dir = fake_active_user / 'demo_vscode'

    RosProjectCreator(
        project_id='demo_vscode',
        project_dir=project_dir,
        ros_distro='jazzy',
        base_img='ros:jazzy',
        image_main_user='developer',
        img_id='demo/vscode:latest',
        use_vscode_project=True,
        use_pre_commit=False,
        use_console_log=False,
    )

    generated_files = [
        project_dir / '.devcontainer/devcontainer.json',
        project_dir / '.devcontainer/docker-compose.yaml',
        project_dir / '.vscode/c_cpp_properties.json',
        project_dir / '.vscode/tasks.json',
        project_dir / 'ws.code-workspace',
    ]

    for generated_file in generated_files:
        assert generated_file.is_file()
        text = generated_file.read_text()
        assert '{{' not in text
        assert '}}' not in text

    assert 'demo/vscode:latest' in project_dir.joinpath('.devcontainer/docker-compose.yaml').read_text()
    assert '"remoteUser": "developer"' in project_dir.joinpath('.devcontainer/devcontainer.json').read_text()
    assert '"ROS2.distro": "jazzy"' in project_dir.joinpath('ws.code-workspace').read_text()


def test_rejects_root_image_user(fake_active_user: Path, fake_docker_generator) -> None:
    with pytest.raises(RosProjectCreatorException, match="Image user 'root' is not supported"):
        RosProjectCreator(
            project_id='demo',
            project_dir=fake_active_user / 'root_user',
            ros_distro='jazzy',
            base_img='ros:jazzy',
            image_main_user='root',
            img_id='demo:latest',
            use_pre_commit=False,
            use_console_log=False,
        )

    assert fake_docker_generator == []


def test_rejects_unsupported_ros_distro(fake_active_user: Path, fake_docker_generator) -> None:
    with pytest.raises(RosProjectCreatorException, match='Allowed ROS distros'):
        RosProjectCreator(
            project_id='demo',
            project_dir=fake_active_user / 'noetic',
            ros_distro='noetic',
            base_img='ros:noetic',
            image_main_user='developer',
            img_id='demo:latest',
            use_pre_commit=False,
            use_console_log=False,
        )

    assert fake_docker_generator == []


@pytest.mark.parametrize(
    ('field_name', 'field_value'),
    [
        ('project_id', '   '),
        ('base_img', '   '),
        ('image_main_user', '   '),
    ],
)
def test_ros_project_rejects_blank_string_parameters(
    fake_active_user: Path,
    fake_docker_generator,
    field_name: str,
    field_value: str,
) -> None:
    params = {
        'project_id': 'demo',
        'project_dir': fake_active_user / f'blank_{field_name}',
        'ros_distro': 'jazzy',
        'base_img': 'ros:jazzy',
        'image_main_user': 'developer',
        'img_id': 'demo:latest',
        'use_pre_commit': False,
        'use_console_log': False,
    }
    params[field_name] = field_value

    with pytest.raises(RosProjectCreatorException, match='must be a non-empty string'):
        RosProjectCreator(**params)

    assert fake_docker_generator == []


@pytest.mark.parametrize(
    ('field_name', 'field_value'),
    [
        ('project_id', '   '),
        ('img_id', '   '),
        ('img_user', '   '),
    ],
)
def test_vscode_project_rejects_blank_string_parameters(
    tmp_path: Path,
    field_name: str,
    field_value: str,
) -> None:
    params = {
        'project_id': 'demo',
        'ros_distro': 'jazzy',
        'img_id': 'demo:latest',
        'img_user': 'developer',
        'img_user_home': Path('/home/developer'),
        'workspace_dir': tmp_path / 'workspace',
        'img_workspace_dir': Path('/home/developer/workspace'),
        'use_console_log': False,
    }
    params[field_name] = field_value

    with pytest.raises(VscodeProjectCreatorException, match='must be a non-empty string'):
        VscodeProjectCreator(**params)
