import json
import os
from pathlib import Path
import subprocess
from types import SimpleNamespace

import pytest
from robotics_dockers.config import ROS_DISTROS

import ros_project_generator.cli as cli_module
import ros_project_generator.create_ros_project as create_ros_project_module
import ros_project_generator.create_vscode_project as create_vscode_project_module
import ros_project_generator.ros_project_generator as ros_project_generator_module
from ros_project_generator.ros_project_generator import RosProjectCreator
from ros_project_generator.ros_project_generator import RosProjectCreatorException
from ros_project_generator.utilities import Utilities
from ros_project_generator.vscode_project_creator import VscodeProjectCreator
from ros_project_generator.vscode_project_creator import VscodeProjectCreatorException


@pytest.fixture
def fake_active_user(monkeypatch: pytest.MonkeyPatch, tmp_path: Path) -> Path:
    user_home = tmp_path / 'home'
    user_home.mkdir()

    monkeypatch.setenv('USER', 'developer')
    monkeypatch.delenv('SUDO_USER', raising=False)
    monkeypatch.setattr(
        ros_project_generator_module.pwd, 'getpwnam', lambda username: SimpleNamespace(pw_dir=str(user_home))
    )

    return user_home


@pytest.fixture
def fake_docker_generator(monkeypatch: pytest.MonkeyPatch):
    calls = []

    def generate_docker_context(config):
        calls.append(config)
        output_dir = Path(config.output_dir)
        output_dir.mkdir(parents=True)
        output_dir.joinpath('Dockerfile').write_text('# generated by robotics_dockers\n')
        output_dir.joinpath('build.py').write_text('# generated by robotics_dockers\n')
        output_dir.joinpath('env_files').mkdir()
        output_dir.joinpath('env_files/.gitkeep').touch()
        output_dir.joinpath('.resources').mkdir()
        return SimpleNamespace(context_dir=output_dir, resolved_config=SimpleNamespace())

    monkeypatch.setattr(ros_project_generator_module, 'generate_docker_context', generate_docker_context)
    return calls


def _create_project(project_dir: Path, **overrides) -> None:
    arguments = {
        'project_id': 'demo',
        'project_dir': project_dir,
        'ros_distro': 'jazzy',
        'base_img': 'ubuntu:24.04',
        'img_id': 'demo:latest',
        'use_vscode_project': False,
        'use_pre_commit': False,
        'use_console_log': False,
    }
    arguments.update(overrides)
    RosProjectCreator(**arguments)


def _create_fake_devcontainer_commands(tmp_path: Path) -> tuple[Path, Path]:
    """Create deterministic Docker and VS Code commands for generated-script tests."""
    fake_bin = tmp_path / 'fake-bin'
    fake_bin.mkdir()
    command_log = tmp_path / 'commands.log'

    fake_docker = fake_bin / 'docker'
    fake_docker.write_text(
        """#!/usr/bin/env bash
set -u
printf 'docker' >>"${COMMAND_LOG}"
printf ' %q' "$@" >>"${COMMAND_LOG}"
printf '\n' >>"${COMMAND_LOG}"

if [ "${1:-}" = image ] && [ "${2:-}" = inspect ]; then
    printf '%s\n' '[{"Config":{"Env":[' \\
        '"ROBOTICS_DOCKERS_USER=developer",' \\
        '"ROBOTICS_DOCKERS_USER_ID=21001",' \\
        '"ROBOTICS_DOCKERS_USER_HOME=/home/developer",' \\
        '"ROBOTICS_DOCKERS_USER_PRIMARY_GROUP=robotics",' \\
        '"ROBOTICS_DOCKERS_USER_PRIMARY_GROUP_ID=21002"' \\
        ']}}]'
fi
"""
    )
    fake_docker.chmod(0o755)

    fake_code = fake_bin / 'code'
    fake_code.write_text(
        """#!/usr/bin/env bash
set -u
printf 'code %s\n' "$*" >>"${COMMAND_LOG}"
printf 'identity=%s:%s\n' \\
    "${IMAGE_USER_ID:-}" \\
    "${IMAGE_USER_PRIMARY_GROUP_ID:-}" >>"${COMMAND_LOG}"
printf 'compose-project=%s\n' "${COMPOSE_PROJECT_NAME:-}" >>"${COMMAND_LOG}"
"""
    )
    fake_code.chmod(0o755)

    return fake_bin, command_log


def test_ros_variants_match_robotics_dockers_supported_ubuntu_versions() -> None:
    variants_file = Path(ros_project_generator_module.__file__).parent.joinpath('resources/ros/ros_variants.yaml')
    variants = Utilities.load_yaml(variants_file)

    assert {distro: values['ubuntu_version'] for distro, values in variants.items()} == ROS_DISTROS


def test_create_ros2_project_delegates_docker_generation(fake_active_user: Path, fake_docker_generator) -> None:
    project_dir = fake_active_user / 'demo_project'

    _create_project(project_dir)

    assert len(fake_docker_generator) == 1
    docker_config = fake_docker_generator[0]
    assert docker_config.ros_distro == 'jazzy'
    assert docker_config.img_id == 'demo:latest'
    assert docker_config.output_dir == project_dir / 'docker'
    assert docker_config.rosdep_packages_dir == '../src'
    assert docker_config.add_compose_file is False

    assert project_dir.joinpath('docker/Dockerfile').is_file()
    assert project_dir.joinpath('docker/build.py').is_file()
    assert project_dir.joinpath('docker/compose_files/docker-compose.yaml').is_file()
    assert project_dir.joinpath('docker/env_files/.gitkeep').is_file()
    assert project_dir.joinpath('docker/.resources').is_dir()

    assert project_dir.joinpath('deps.repos').is_file()
    readme_text = project_dir.joinpath('README.md').read_text()
    assert '# demo' in readme_text
    assert 'ROS 2 jazzy project using the Docker image `demo:latest`' in readme_text
    assert 'python3 build.py developer' in readme_text
    assert project_dir.joinpath('src/0_deps').is_dir()
    assert project_dir.joinpath('src/bringup/package.xml').is_file()
    assert project_dir.joinpath('src/simulation/package.xml').is_file()


def test_create_ros2_project_with_vscode_copies_the_project_compose(fake_active_user: Path) -> None:
    project_dir = fake_active_user / 'demo_vscode'

    _create_project(project_dir, img_id='demo/vscode:latest', use_vscode_project=True)

    docker_compose = project_dir / 'docker/compose_files/docker-compose.yaml'
    devcontainer_compose = project_dir / '.devcontainer/docker-compose.yaml'
    devcontainer_file = project_dir / '.devcontainer/devcontainer.json'
    code_devcont_script = project_dir / '.devcontainer/code-devcont'
    devcont_script = project_dir / '.devcontainer/devcont'

    for generated_file in (
        devcontainer_file,
        code_devcont_script,
        devcont_script,
        devcontainer_compose,
        project_dir / '.vscode/c_cpp_properties.json',
        project_dir / '.vscode/tasks.json',
        project_dir / 'ws.code-workspace',
    ):
        assert generated_file.is_file()
        assert '{{ image_name }}' not in generated_file.read_text()

    # Both use cases receive the same complete runtime configuration. They are
    # separate files so a developer can later customize only .devcontainer.
    assert devcontainer_compose.read_bytes() == docker_compose.read_bytes()

    compose_text = devcontainer_compose.read_text()
    compose_config = Utilities.load_yaml(devcontainer_compose)
    assert compose_config['name'] == '${COMPOSE_PROJECT_NAME:-demo}'
    service = next(iter(compose_config['services'].values()))
    workspace_mount = next(
        mount
        for mount in service['volumes']
        if isinstance(mount, dict) and mount.get('source', '').startswith('${HOST_WORKSPACE:')
    )
    assert 'demo/vscode:latest' in compose_text
    assert workspace_mount['type'] == 'bind'
    assert workspace_mount['target'] == '/workspace'
    assert workspace_mount['bind']['create_host_path'] is False
    assert '#   source: "${HOST_WORKSPACE:' not in compose_text
    assert 'CONTAINER_ROS_WORKSPACE: "/workspace"' in compose_text
    assert '# cap_add:' in compose_text
    assert '#   - NET_ADMIN' in compose_text
    assert '# ulimits:' in compose_text
    assert '#   rtprio:' in compose_text
    assert '#   memlock:' in compose_text
    assert service['stop_grace_period'] == '30s'
    assert 'HOST_UID' not in compose_text
    assert 'HOST_UPGID' not in compose_text
    assert 'user: root' not in compose_text
    assert 'driver: nvidia' not in compose_text

    devcontainer = json.loads(devcontainer_file.read_text())
    assert devcontainer['dockerComposeFile'] == 'docker-compose.yaml'
    assert devcontainer['service'] == 'demo_vscode_latest_cont'
    assert devcontainer['updateRemoteUserUID'] is False
    assert devcontainer['overrideCommand'] is False
    assert 'containerUser' not in devcontainer
    assert 'remoteUser' not in devcontainer
    assert devcontainer['workspaceFolder'] == '/workspace'

    assert os.access(code_devcont_script, os.X_OK)
    assert os.access(devcont_script, os.X_OK)
    assert 'HOST_WORKSPACE' in code_devcont_script.read_text()
    assert 'HOST_WORKSPACE' in devcont_script.read_text()
    assert 'IMAGE_USER_ID' in code_devcont_script.read_text()
    assert 'IMAGE_USER_PRIMARY_GROUP_ID' in code_devcont_script.read_text()
    assert 'robotics_dockers_user_env.py' in code_devcont_script.read_text()
    assert 'IMAGE_USER_ID' in devcont_script.read_text()
    assert 'IMAGE_USER_PRIMARY_GROUP_ID' in devcont_script.read_text()
    assert 'robotics_dockers_user_env.py' in devcont_script.read_text()
    assert 'COMPOSE_PROJECT_NAME="${COMPOSE_PROJECT_NAME:-demo}"' in code_devcont_script.read_text()
    assert 'print_compose_env_assignment COMPOSE_PROJECT_NAME' in devcont_script.read_text()
    assert 'docker image inspect' not in code_devcont_script.read_text()
    assert 'docker image inspect' not in devcont_script.read_text()
    assert 'HOST_UID' not in code_devcont_script.read_text()
    assert 'HOST_UPGID' not in devcont_script.read_text()
    assert not project_dir.joinpath('.devcontainer/.env').exists()

    # Editor and Dev Container files are per-developer starting points. The
    # generated repository must not start tracking later local customizations.
    gitignore_lines = project_dir.joinpath('.gitignore').read_text().splitlines()
    assert '.devcontainer/' in gitignore_lines
    assert '.vscode/' in gitignore_lines
    assert '*.code-workspace' in gitignore_lines


def test_devcontainer_compose_is_independent_after_initial_copy(fake_active_user: Path) -> None:
    project_dir = fake_active_user / 'independent_compose'
    _create_project(project_dir, use_vscode_project=True)

    docker_compose = project_dir / 'docker/compose_files/docker-compose.yaml'
    devcontainer_compose = project_dir / '.devcontainer/docker-compose.yaml'
    original_docker_compose = docker_compose.read_text()

    devcontainer_compose.write_text(devcontainer_compose.read_text() + '\n# Local developer customization.\n')

    assert docker_compose.read_text() == original_docker_compose
    assert devcontainer_compose.read_text() != docker_compose.read_text()


def test_code_devcont_exports_image_identity_without_writing_env(fake_active_user: Path, tmp_path: Path) -> None:
    project_dir = fake_active_user / 'code_devcontainer'
    _create_project(project_dir, use_vscode_project=True)
    fake_bin, command_log = _create_fake_devcontainer_commands(tmp_path)
    xauthority_file = tmp_path / 'docker-xwayland.xauth'
    render_device = tmp_path / 'renderD128'
    xauthority_file.touch()
    render_device.touch()
    environment = os.environ.copy()
    environment.update(
        {
            'COMMAND_LOG': str(command_log),
            'DISPLAY': ':99',
            'HOST_XAUTHORITY_FILE': str(xauthority_file),
            'PATH': f'{fake_bin}:{environment["PATH"]}',
            'RENDER_DEVICE': str(render_device),
        }
    )

    completed = subprocess.run(
        [str(project_dir / '.devcontainer/code-devcont')], text=True, capture_output=True, env=environment
    )

    assert completed.returncode == 0, completed.stdout + completed.stderr
    command_output = command_log.read_text()
    assert 'docker image inspect' in command_output
    assert 'identity=21001:21002' in command_output
    assert 'compose-project=demo' in command_output
    assert f'code {project_dir / "ws.code-workspace"}' in command_output
    assert not project_dir.joinpath('.devcontainer/.env').exists()
    assert not project_dir.joinpath('docker/.env').exists()


def test_devcont_up_writes_only_development_env_from_image(fake_active_user: Path, tmp_path: Path) -> None:
    project_dir = fake_active_user / 'compose_devcontainer'
    _create_project(project_dir, use_vscode_project=True)
    fake_bin, command_log = _create_fake_devcontainer_commands(tmp_path)
    xauthority_file = tmp_path / 'docker-xwayland.xauth'
    render_device = tmp_path / 'renderD128'
    xauthority_file.touch()
    render_device.touch()
    environment = os.environ.copy()
    environment.update(
        {
            'COMMAND_LOG': str(command_log),
            'DISPLAY': ':99',
            'HOST_XAUTHORITY_FILE': str(xauthority_file),
            'PATH': f'{fake_bin}:{environment["PATH"]}',
            'RENDER_DEVICE': str(render_device),
        }
    )

    completed = subprocess.run(
        [str(project_dir / '.devcontainer/devcont'), '--up'], text=True, capture_output=True, env=environment
    )

    assert completed.returncode == 0, completed.stdout + completed.stderr
    development_env = project_dir.joinpath('.devcontainer/.env')
    assert development_env.is_file()
    assert development_env.stat().st_mode & 0o777 == 0o600
    assert development_env.read_text().splitlines() == [
        '# Generated by devcont --up. Local machine values; do not commit.',
        "COMPOSE_PROJECT_NAME='demo'",
        "IMAGE_USER_ID='21001'",
        "IMAGE_USER_PRIMARY_GROUP_ID='21002'",
        f"HOST_WORKSPACE='{project_dir}'",
        f"HOST_XAUTHORITY_FILE='{xauthority_file}'",
        f"RENDER_GID='{render_device.stat().st_gid}'",
        "DISPLAY=':99'",
    ]
    assert not project_dir.joinpath('docker/.env').exists()
    command_output = command_log.read_text()
    assert 'docker image inspect' in command_output
    assert 'docker compose version' in command_output
    assert 'docker compose --project-directory' in command_output
    assert 'docker-compose.yaml up -d' in command_output


def test_devcont_env_preserves_special_path_characters(fake_active_user: Path, tmp_path: Path) -> None:
    project_dir = fake_active_user / 'compose_special_values'
    _create_project(project_dir, use_vscode_project=True)
    fake_bin, command_log = _create_fake_devcontainer_commands(tmp_path)
    xauthority_file = tmp_path / "authority file #1 $USER's.xauth"
    render_device = tmp_path / 'renderD128'
    xauthority_file.touch()
    render_device.touch()
    environment = os.environ.copy()
    environment.update(
        {
            'COMMAND_LOG': str(command_log),
            'DISPLAY': ':99',
            'HOST_XAUTHORITY_FILE': str(xauthority_file),
            'PATH': f'{fake_bin}:{environment["PATH"]}',
            'RENDER_DEVICE': str(render_device),
        }
    )

    completed = subprocess.run(
        [str(project_dir / '.devcontainer/devcont'), '--up'], text=True, capture_output=True, env=environment
    )

    assert completed.returncode == 0, completed.stdout + completed.stderr
    development_env = project_dir.joinpath('.devcontainer/.env').read_text()
    escaped_path = str(xauthority_file).replace("'", "\\'")
    assert f"HOST_XAUTHORITY_FILE='{escaped_path}'" in development_env
    assert 'HOST_XAUTHORITY_FILE=/tmp/' not in development_env


def test_devcont_down_reuses_existing_development_env(fake_active_user: Path, tmp_path: Path) -> None:
    project_dir = fake_active_user / 'stop_devcontainer'
    _create_project(project_dir, use_vscode_project=True)
    fake_bin, command_log = _create_fake_devcontainer_commands(tmp_path)
    development_env = project_dir / '.devcontainer/.env'
    existing_contents = (
        'COMPOSE_PROJECT_NAME=stop_devcontainer\n'
        'IMAGE_USER_ID=21001\n'
        'IMAGE_USER_PRIMARY_GROUP_ID=21002\n'
        f'HOST_WORKSPACE={project_dir}\n'
        'HOST_XAUTHORITY_FILE=/tmp/docker-xwayland.xauth\n'
        'RENDER_GID=992\n'
        'DISPLAY=:99\n'
    )
    development_env.write_text(existing_contents)
    environment = os.environ.copy()
    environment.update({'COMMAND_LOG': str(command_log), 'PATH': f'{fake_bin}:{environment["PATH"]}'})

    completed = subprocess.run(
        [str(project_dir / '.devcontainer/devcont'), '--down'], text=True, capture_output=True, env=environment
    )

    assert completed.returncode == 0, completed.stdout + completed.stderr
    assert development_env.read_text() == existing_contents
    command_output = command_log.read_text()
    assert 'docker image inspect' not in command_output
    assert 'docker compose version' in command_output
    assert 'docker compose --project-directory' in command_output
    assert 'docker-compose.yaml down' in command_output


def test_nvidia_configuration_is_copied_when_requested(fake_active_user: Path) -> None:
    project_dir = fake_active_user / 'nvidia_project'
    _create_project(project_dir, use_vscode_project=True, use_host_nvidia_driver=True)

    compose_text = project_dir.joinpath('.devcontainer/docker-compose.yaml').read_text()
    assert 'driver: nvidia' in compose_text
    assert 'capabilities: [gpu]' in compose_text
    assert 'NVIDIA_VISIBLE_DEVICES: "all"' in compose_text
    assert 'NVIDIA_DRIVER_CAPABILITIES: "all"' in compose_text


def test_rejects_unsupported_ros_distro(fake_active_user: Path, fake_docker_generator) -> None:
    with pytest.raises(RosProjectCreatorException, match='Allowed ROS distros'):
        _create_project(fake_active_user / 'noetic', ros_distro='noetic')

    assert fake_docker_generator == []


@pytest.mark.parametrize('project_id', ['Demo', 'my.robot', '-demo', '_demo', 'demo project'])
def test_rejects_project_id_that_compose_cannot_use(
    project_id: str, fake_active_user: Path, fake_docker_generator
) -> None:
    with pytest.raises(RosProjectCreatorException, match='Project id must start with a lowercase letter or digit'):
        _create_project(fake_active_user / 'invalid_project', project_id=project_id)

    assert fake_docker_generator == []


@pytest.mark.parametrize('project_id', ['demo', '9demo', 'demo-1', 'demo_1'])
def test_accepts_project_id_that_compose_can_use(
    project_id: str, fake_active_user: Path, fake_docker_generator
) -> None:
    _create_project(fake_active_user / project_id, project_id=project_id)

    assert len(fake_docker_generator) == 1


def test_rejects_blank_project_dir(fake_active_user: Path, fake_docker_generator) -> None:
    with pytest.raises(RosProjectCreatorException, match='Project directory must be a non-empty path'):
        _create_project(Path('   '))

    assert fake_docker_generator == []


def test_rejects_relative_project_dir_outside_active_user_home(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path, fake_active_user: Path, fake_docker_generator
) -> None:
    outside_home = tmp_path / 'outside_home'
    outside_home.mkdir()
    monkeypatch.chdir(outside_home)

    with pytest.raises(RosProjectCreatorException, match='Project directory must be inside'):
        _create_project(Path('demo_project'))

    assert fake_docker_generator == []


def test_dot_project_dir_resolves_before_home_check(
    monkeypatch: pytest.MonkeyPatch, fake_active_user: Path, fake_docker_generator
) -> None:
    monkeypatch.chdir(fake_active_user)

    with pytest.raises(RosProjectCreatorException, match='already exists'):
        _create_project(Path('.'))

    assert fake_docker_generator == []


def test_vscode_project_rejects_compose_with_multiple_services(tmp_path: Path) -> None:
    workspace_dir = tmp_path / 'workspace'
    workspace_dir.mkdir()
    compose_file = workspace_dir / 'compose.yaml'
    compose_file.write_text('services:\n  first: {}\n  second: {}\n')

    with pytest.raises(VscodeProjectCreatorException, match='exactly one service'):
        VscodeProjectCreator(
            project_id='demo',
            ros_distro='jazzy',
            workspace_dir=workspace_dir,
            source_compose_file=compose_file,
            use_console_log=False,
        )


def test_vscode_project_rejects_invalid_compose_project_id_before_installing_files(tmp_path: Path) -> None:
    workspace_dir = tmp_path / 'workspace'
    workspace_dir.mkdir()

    with pytest.raises(VscodeProjectCreatorException, match='Project id must start with a lowercase letter or digit'):
        VscodeProjectCreator(
            project_id='Invalid.Project',
            ros_distro='jazzy',
            workspace_dir=workspace_dir,
            source_compose_file=workspace_dir / 'missing-compose.yaml',
            use_console_log=False,
        )

    assert list(workspace_dir.iterdir()) == []


def test_create_ros_project_cli_forwards_shared_image_configuration(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    calls = []
    monkeypatch.setattr(create_ros_project_module, 'RosProjectCreator', lambda **kwargs: calls.append(kwargs))

    create_ros_project_module.main(['demo', str(tmp_path / 'demo'), 'jazzy', '--base-img', 'ubuntu:24.04'])

    assert calls[0]['ros_distro'] == 'jazzy'
    assert calls[0]['base_img'] == 'ubuntu:24.04'


def test_ros_project_cli_new_delegates_to_project_creator(monkeypatch: pytest.MonkeyPatch, tmp_path: Path) -> None:
    calls = []

    def create_project(argv, prog=None):
        calls.append((argv, prog))

    monkeypatch.setattr(cli_module.create_ros_project, 'main', create_project)
    arguments = ['demo', str(tmp_path / 'demo'), 'jazzy']

    cli_module.main(['new', *arguments])

    assert calls == [(arguments, 'ros-project new')]


def test_create_vscode_project_cli_uses_generated_compose_by_default(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    calls = []
    workspace_dir = tmp_path / 'workspace'
    monkeypatch.setattr(create_vscode_project_module, 'VscodeProjectCreator', lambda **kwargs: calls.append(kwargs))

    create_vscode_project_module.main(['demo', str(workspace_dir), 'jazzy'])

    assert calls[0]['project_id'] == 'demo'
    assert calls[0]['workspace_dir'] == workspace_dir
    assert calls[0]['source_compose_file'] == workspace_dir / 'docker/compose_files/docker-compose.yaml'
