# syntax=docker/dockerfile:1

# No default base_img is provided to ensure the build process fails if no base_img is specified.
# The warning 'InvalidDefaultArgInFrom: Default value for ARG ${base_img} results in empty or
# invalid base image name' can be safely ignored, as this behavior is intentional.
FROM {{ base_img }}

# The following labels adhere to the OCI Image Specification for standardized metadata.
# Reference: https://github.com/opencontainers/image-spec/blob/main/annotations.md
LABEL org.opencontainers.image.title="Project Docker Image" \
    org.opencontainers.image.description="A Docker image for development and testing" \
    org.opencontainers.image.authors="anon"

ENV IMAGE_MAIN_USER="{{ image_main_user }}" \
    ROS_DISTRO="{{ ros_distro }}" \
    ROS_VERSION="{{ ros_version }}" \
    DEBIAN_FRONTEND="noninteractive"

USER root
WORKDIR /root

SHELL ["/bin/bash", "-c"]

# Avoid installing recommended and suggested packages.
RUN tee /etc/apt/apt.conf.d/99norecommends.conf >/dev/null <<'EOF'
APT::Install-Recommends "false";
APT::Install-Suggests "false";
EOF

COPY --chmod=755 docker/.resources/install_base_system.sh /tmp/
RUN /tmp/install_base_system.sh "${IMAGE_MAIN_USER}" && rm -f /tmp/install_base_system.sh

COPY --chmod=755 docker/.resources/install_ros.sh /tmp/
RUN /tmp/install_ros.sh "${ROS_DISTRO}" "${ROS_VERSION}" && rm -f /tmp/install_ros.sh

# The following block is always re-executed and is NOT cached intentionally.
# It uses the --mount=type=bind option to bind the current context to the container, since the context has, most of the
# time, a significant amount of files that do not need to be copied, and subsequently occupying space in the associated
# layer.
RUN --mount=type=bind,source=.,target=/tmp/context <<'EOF'
log() { echo "[$(date --utc '+%Y-%m-%d_%H-%M-%S')]" "$@"; }

image_main_user_entry="$(getent passwd "${IMAGE_MAIN_USER}")"

[ -z "${image_main_user_entry}" ] && { log "Error: User '${IMAGE_MAIN_USER}' not found" >&2; exit 1; }

{% if not use_base_img_entrypoint %}
[ ! -f /tmp/context/docker/entrypoint.sh ] && { log "Error: Script entrypoint.sh not provided" >&2; exit 1; }
{% endif %}

{% if use_environment %}
[ ! -f /tmp/context/docker/.resources/environment.sh ] && { log "Error: Script environment.sh not provided" >&2; exit 1; }
{% endif %}

[ ! -f /tmp/context/docker/.resources/deduplicate_path.sh ] && {
    log "Error: Script deduplicate_path.sh not provided" >&2
    exit 1
}

[ ! -f /tmp/context/docker/.resources/rosbuild.sh ] && {
    log "Error: Script rosbuild.sh not provided" >&2
    exit 1
}

[ ! -f /tmp/context/docker/.resources/rosdep_init_update_install.sh ] && {
    log "Error: Script rosdep_init_update_install.sh not provided" >&2
    exit 1
}

[ ! -f /tmp/context/docker/.resources/colcon_mixin_metadata.sh ] && {
    log "Error: Script colcon_mixin_metadata.sh not provided" >&2
    exit 1
}

# Check if ${ROS_DISTRO} is installed properly, otherwise abort the installation.
ros_distro="$(dpkg-query -W -f='${binary:Package}\n' 'ros-*-ros-core' | cut -d'-' -f2 | paste -sd' ' -)"
num_distros=$(echo "${ros_distro}" | wc -w)

# If no ROS_DISTRO is found at this point, exit with an error.
[ "${num_distros}" -eq 0 ] && {
    log "Error: No ROS distribution found" >&2
    exit 1
}

[ "${num_distros}" -gt 1 ] && {
    log "Error: More than one ROS_DISTRO found: ${ros_distro}" >&2
    exit 1
}

[ "${ROS_DISTRO}" != "${ros_distro}" ] && {
    log "Error: Found ROS_DISTRO '${ros_distro}', expected ROS_DISTRO '${ROS_DISTRO}'" >&2
    exit 1
}

etc_rosdep_dir="/etc/ros/rosdep"
etc_rosdep_sources_dir="${etc_rosdep_dir}/sources.list.d"
mkdir --verbose --parent "${etc_rosdep_sources_dir}"

# Define file where rosdep keys to skip are saved.
# Array 'rosdep_ignored_keys' can add keys to this file.
# The script 'install_extras.sh' can also add keys to this file.
rosdep_ignored_keys_file="${etc_rosdep_dir}/rosdep_ignored_keys.yaml"

# Make sure the file exists.
touch "${rosdep_ignored_keys_file}"

# Index file listing the files with rosdep keys to skip, and read by rosdep.
# In this case we have opted to save all the keys to skip in a single file, '${rosdep_ignored_keys_file}'.
rosdep_ignored_keys_index_file="${etc_rosdep_sources_dir}/00-rosdep-ignored-keys-index.list"

# Make sure the index file exists.
touch "${rosdep_ignored_keys_index_file}"

# Add the line indicating the file with rosdep keys to ignore to the index file, if not already present.
line="yaml file://${rosdep_ignored_keys_file}"

# -q, --quiet: Suppress normal output.
# -x, --line-regexp: Select only those matches that exactly match the whole line.
# -F, --fixed-strings: Interpret the pattern as fixed strings, not regular expressions.
if ! grep -qxF "${line}" "${rosdep_ignored_keys_index_file}"; then
  echo "${line}" >>"${rosdep_ignored_keys_index_file}"
  log "Added line '${line}' to file '${rosdep_ignored_keys_index_file}'"
else
  log "Line '${line}' already exists in the rosdep ignored keys index file '${rosdep_ignored_keys_index_file}'. Skipping adding it again."
fi

# Initial rosdep keys to skip.
{% set skip = rosdep_ignored_keys | default([], true) %}
{% if skip %}
rosdep_ignored_keys=(
{% for k in skip %}
  "{{ k }}"
{% endfor %}
)
{% else %}
rosdep_ignored_keys=()
{% endif %}

# -q, --quiet: Suppress normal output.
# -x, --line-regexp: Select only those matches that exactly match the whole line.
# -F, --fixed-strings: Interpret the pattern as fixed strings, not regular expressions.
for key in "${rosdep_ignored_keys[@]}"; do
    if ! grep -qxF "${key}" "${rosdep_ignored_keys_file}"; then
        printf '%s\n' "${key}" >>"${rosdep_ignored_keys_file}"
        log "Added rosdep key to ignore, '${key}', to file '${rosdep_ignored_keys_file}'"
    else
        log "Rosdep key to ignore '${key}' already exists in file '${rosdep_ignored_keys_file}'. Skipping adding it again."
    fi
done

pkgs_dir="/tmp/context/src"

# Execute the custom dependency install script for the project.
# This file could add rosdep keys to ignore to the file '${rosdep_ignored_keys_file}'.
if [ -s /tmp/context/install_extras.sh ]; then
    bash /tmp/context/install_extras.sh --ignored-keys-file "${rosdep_ignored_keys_file}" \
        --pkgs-dir "${pkgs_dir}" \
        --ros-distro "${ROS_DISTRO}" \
        --target-user "${IMAGE_MAIN_USER}" || {
        log "Error: Failed to run install_extras.sh" >&2
        exit 1
    }
fi

# Now that all the rosdep keys to ignore have been added to the file '${rosdep_ignored_keys_file}',
# check if the file is empty, and if so remove it and the corresponding line in the index file.
# If the file with rosdep keys to ignore is empty remove it.
if [ "$(stat -c %s "${rosdep_ignored_keys_file}")" -eq 0 ]; then
    rm -f "${rosdep_ignored_keys_file}" || {
        log "Error: Failed to remove empty file '${rosdep_ignored_keys_file}'" >&2
        exit 1
    }

    log "Removed empty file '${rosdep_ignored_keys_file}'"

    # Remove the corresponding line in the index file.
    # The file is removed in two steps to avoid issues with in-place editing.
    # First create a temporary file without the line to remove, then move it to overwrite the original file.
    # mv is atomic, so no issues with in-place editing will occur.
    awk -v t="${line}" '$0 != t' "${rosdep_ignored_keys_index_file}" > "${rosdep_ignored_keys_index_file}.tmp"
    mv "${rosdep_ignored_keys_index_file}.tmp" "${rosdep_ignored_keys_index_file}"

    log "Removed line '${line}' from file '${rosdep_ignored_keys_index_file}'"
fi

# Also check if the index file is empty, and if so remove it.
if [ "$(stat -c %s "${rosdep_ignored_keys_index_file}")" -eq 0 ]; then
    rm -f "${rosdep_ignored_keys_index_file}" || {
        log "Error: Failed to remove empty file '${rosdep_ignored_keys_index_file}'" >&2
        exit 1
    }

    log "Removed empty file '${rosdep_ignored_keys_index_file}'"
fi

rosdep_args=("${ROS_DISTRO}" "${IMAGE_MAIN_USER}" --pkgs-dir "${pkgs_dir}")
bash /tmp/context/docker/.resources/rosdep_init_update_install.sh "${rosdep_args[@]}" || {
    log "Error: Failed to run rosdep_init_update_install.sh" >&2
    exit 1
}

bash /tmp/context/docker/.resources/colcon_mixin_metadata.sh "${IMAGE_MAIN_USER}" || {
    log "Error: Failed run colcon_mixin_metadata.sh" >&2
    exit 1
}

image_main_user_id="$(echo "${image_main_user_entry}" | cut -d: -f3)"
image_main_user_pri_group_id="$(echo "${image_main_user_entry}" | cut -d: -f4)"
image_main_user_pri_group="$(getent group "${image_main_user_pri_group_id}" | cut -d: -f1)"
image_main_user_home="$(echo "${image_main_user_entry}" | cut -d: -f6)"

{% if use_environment %}
# Check if the ${env_line} exists in the file bashrc files.
env_line='[ -f "${HOME}/.environment.sh" ] && . "${HOME}/.environment.sh"'

if ! grep -Fxq "${env_line}" "${image_main_user_home}/.bashrc"; then
    log "Adding line '${env_line}' to file '${image_main_user_home}/.bashrc'"
    echo '# --------------------------------------' >> "${image_main_user_home}/.bashrc"
    echo "${env_line}" >> "${image_main_user_home}/.bashrc"
else
    log "Line '${env_line}' already exists in file '${image_main_user_home}/.bashrc'"
fi

# An environment script is installed in the home directory of the '${IMAGE_MAIN_USER}'.
log "Installing file '${image_main_user_home}/.environment.sh'"
install --owner "${IMAGE_MAIN_USER}" --group "${image_main_user_pri_group}" --mode 775 /tmp/context/docker/.resources/environment.sh "${image_main_user_home}/.environment.sh"
{% endif %}

# Every file and folder in image_main_user_home must belong to the IMAGE_MAIN_USER.
log "Setting ownership of path '${image_main_user_home}' to user '${IMAGE_MAIN_USER}' (UID '${image_main_user_id}') and primary group '${image_main_user_pri_group}' (GID '${image_main_user_pri_group_id}')"
chown --recursive "${IMAGE_MAIN_USER}":"${image_main_user_pri_group}" "${image_main_user_home}"

{% if not use_base_img_entrypoint %}
log "Installing file '/usr/local/bin/entrypoint.sh'" >&2
install --owner root --group root --mode 775 /tmp/context/docker/entrypoint.sh /usr/local/bin/entrypoint.sh
{% endif %}

log "Installing file '/usr/local/bin/deduplicate_path.sh'"
install --owner root --group root --mode 775 /tmp/context/docker/.resources/deduplicate_path.sh /usr/local/bin/deduplicate_path.sh

log "Installing file '/usr/local/bin/rosbuild.sh'"
install --owner root --group root --mode 775 /tmp/context/docker/.resources/rosbuild.sh /usr/local/bin/rosbuild.sh

# Optional: install .bash_aliases if present
[ -e /tmp/context/docker/.resources/dot_bash_aliases ] && \
  install --owner "${IMAGE_MAIN_USER}" --group "${image_main_user_pri_group}" --mode 775 /tmp/context/docker/.resources/dot_bash_aliases "${image_main_user_home}/.bash_aliases"

log "Removing installation residues from apt cache"
apt-get autoclean
apt-get autoremove --purge -y
apt-get clean
rm -rf /var/lib/apt/lists/* &>/dev/null
EOF

# Configure timezone and localization settings.
# - TZ: Set the timezone to UTC to ensure consistent time handling across environments.
# - LC_ALL, LANG, LANGUAGE: Configure localization to US English and UTF-8 encoding, which helps
#   avoiding issues with character encoding and ensures compatibility with most tools and libraries.
ENV TZ="Etc/UTC" \
    LC_ALL="en_US.UTF-8" \
    LANG="en_US.UTF-8" \
    LANGUAGE="en_US:en" \
    ROS_HOME="{{ image_main_user_home }}/.ros" \
    ROS_LOG_DIR="{{ image_main_user_home }}/.ros/logs" \
    ROS_TEST_RESULTS_DIR="{{ image_main_user_home }}/.ros/tests" \
    ROS_CONFIG_HOME="{{ image_main_user_home }}/.config/ros.org" \
    {{ extra_ros_env_vars }}

USER "${IMAGE_MAIN_USER}"
WORKDIR "/"
{% if not use_base_img_entrypoint -%}
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
{% endif -%}
CMD ["bash"]
